[package]
name = "rust_lib_zk_notion_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
automerge = { version = "0.6.1" }
anyhow = "1.0.99"
sha2 = "0.10.9"
awesome-client-sdk = { git = "ssh://git@github.com/zk-messenger/awesome-client-sdk.git", branch = "dev" }
zk = { git = "ssh://git@github.com/zk-messenger/project-m.git", branch = "art-dev" }
art = { git = "ssh://git@github.com/zk-messenger/project-m.git", branch = "art-dev" }
crypto = { git = "ssh://git@github.com/zk-messenger/project-m.git", branch = "art-dev" }
cortado = { git = "ssh://git@github.com/zk-messenger/project-m.git", branch = "art-dev" }
bulletproofs = { version = "5.0.0", git="https://github.com/zk-messenger/bulletproofs"}
ark-serialize = "0.5.0"
prost = "0.14.1"
prost-types = "0.14.1"
ark-ec = "0.5.0"
chrono = "0.4.42"
sha3 = "0.10.8"

[patch.crates-io]
aead = { path = "./patches/aead-0.5.2-fixed" }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
