// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BAutoCommit>>
abstract class BAutoCommit implements RustOpaqueInterface {
  static BAutoCommit fromBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiAutomergeBAutoCommitFromBytes(bytes: bytes);

  String info();

  factory BAutoCommit() =>
      RustLib.instance.api.crateApiAutomergeBAutoCommitNew();

  void putRootObject({required String label, required BObjType value});

  Uint8List save();
}

enum BObjType {
  /// A map
  map,

  /// Retained for backwards compatibility, tables are identical to maps
  table,

  /// A sequence of arbitrary values
  list,

  /// A sequence of characters
  text,
}
