// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_list_exist`, `blocks_list_id`, `new`, `setup_block_label`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

String generateActorId() =>
    RustLib.instance.api.crateApiAutomergeGenerateActorId();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BAutoCommit>>
abstract class BAutoCommit implements RustOpaqueInterface {
  BigInt blocksLength();

  void commit();

  void deleteBlock({required BigInt index});

  BAutoCommit docAtChangeHash({required String changeHash});

  (BAutoCommit, BAutoCommit) docsBeforeAfter({required String changeHash});

  void emptyChange();

  BAutoCommit fork();

  static BAutoCommit fromBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiAutomergeBAutoCommitFromBytes(bytes: bytes);

  /// For tests only
  Future<void> getAutomerge();

  List<String> getBlocks();

  List<BChange> getChangeList();

  String info();

  /// Insert block at specific index.
  /// If index is duplicate it will add new value at this index and previous value will be moved to next index
  void insertBlock({required BigInt index, required String text});

  static BAutoCommit load({required List<int> data}) =>
      RustLib.instance.api.crateApiAutomergeBAutoCommitLoad(data: data);

  BigInt loadIncremental({required List<int> bytes});

  factory BAutoCommit() =>
      RustLib.instance.api.crateApiAutomergeBAutoCommitNew();

  Uint8List save();

  Uint8List saveIncremental();

  void setActorId({required String uuid});

  /// If content is the same nothing will be changed. Returns true if content was changed, othervise false
  void updateBlock({required BigInt index, required String text});

  static BAutoCommit withOwner({required String actorId}) => RustLib
      .instance
      .api
      .crateApiAutomergeBAutoCommitWithOwner(actorId: actorId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BChange>>
abstract class BChange implements RustOpaqueInterface {
  String actorIdHex();

  String changeHash();

  PlatformInt64 timestamp();
}
