// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initTracing() => RustLib.instance.api.crateApiGroupContextInitTracing();

String hashPublicKey({required List<int> pk}) =>
    RustLib.instance.api.crateApiGroupContextHashPublicKey(pk: pk);

Uint8List publicKeyFromSecretKey({required List<int> secretKey}) => RustLib
    .instance
    .api
    .crateApiGroupContextPublicKeyFromSecretKey(secretKey: secretKey);

(BGroupContext, Uint8List) createGroup({
  required List<int> identitySecretKey,
  required BUser user,
  required BGroupInfo groupInfo,
}) => RustLib.instance.api.crateApiGroupContextCreateGroup(
  identitySecretKey: identitySecretKey,
  user: user,
  groupInfo: groupInfo,
);

String hashPublcihKey({required List<int> pk}) =>
    RustLib.instance.api.crateApiGroupContextHashPublcihKey(pk: pk);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BGroupContext>>
abstract class BGroupContext implements RustOpaqueInterface {
  (Uint8List, Uint8List) addIdentifiedMember({
    required List<int> identityPublicKey,
    Uint8List? spkPublicKey,
    required List<Uint8List> payloads,
  });

  Future<(Uint8List, Uint8List)> addUnidentifiedMember({
    required List<int> secretKey,
    required List<Uint8List> payloads,
  });

  void commitState();

  Uint8List createFrame({required List<Uint8List> payloads});

  static BGroupContext fromParts({
    required List<int> identitySecretKey,
    required List<int> leafSecret,
    required List<int> art,
    required List<int> stk,
    required BigInt epoch,
    required List<int> groupInfo,
    required bool isLastSender,
  }) => RustLib.instance.api.crateApiGroupContextBGroupContextFromParts(
    identitySecretKey: identitySecretKey,
    leafSecret: leafSecret,
    art: art,
    stk: stk,
    epoch: epoch,
    groupInfo: groupInfo,
    isLastSender: isLastSender,
  );

  BigInt getEpoch();

  Uint8List getGroupInfo();

  (Uint8List, Uint8List, Uint8List, BigInt, Uint8List, bool) intoParts();

  List<Uint8List> processFrame({required List<int> frame});

  Uint8List signChallenge({required List<int> challenge});

  Uint8List signWithTk({required String groupId, required List<int> nonce});

  (Uint8List, Uint8List, Uint8List, BigInt, Uint8List, bool) toParts();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BGroupInfo>>
abstract class BGroupInfo implements RustOpaqueInterface {
  String id();

  String name();

  factory BGroupInfo({required String id, required String name}) => RustLib
      .instance
      .api
      .crateApiGroupContextBGroupInfoNew(id: id, name: name);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BInviteContext>>
abstract class BInviteContext implements RustOpaqueInterface {
  BigInt epoch();

  String groupId();

  Uint8List leafPublicKey();

  factory BInviteContext({
    required List<int> identitySecretKey,
    required List<int> spkSecretKey,
    required List<int> invite,
  }) => RustLib.instance.api.crateApiGroupContextBInviteContextNew(
    identitySecretKey: identitySecretKey,
    spkSecretKey: spkSecretKey,
    invite: invite,
  );

  Uint8List signAsIdentity({required List<int> msg});

  Uint8List signAsLeaf({required List<int> msg});

  Uint8List signChallenge({
    required List<int> nonce,
    required List<int> challenge,
  });

  BPendingGroupContext upgrade({required List<int> publicArt});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BPendingGroupContext>>
abstract class BPendingGroupContext implements RustOpaqueInterface {
  static BPendingGroupContext fromParts({
    required List<int> identitySecretKey,
    required List<int> leafSecret,
    required List<int> art,
    required List<int> stk,
    required BigInt epoch,
    required List<int> groupInfo,
    required bool isLastSender,
  }) => RustLib.instance.api.crateApiGroupContextBPendingGroupContextFromParts(
    identitySecretKey: identitySecretKey,
    leafSecret: leafSecret,
    art: art,
    stk: stk,
    epoch: epoch,
    groupInfo: groupInfo,
    isLastSender: isLastSender,
  );

  BigInt getEpoch();

  Uint8List getGroupInfo();

  (Uint8List, Uint8List, Uint8List, BigInt, Uint8List, bool) intoParts();

  Uint8List joinGroupAs({required BUser user});

  List<Uint8List> processFrame({required List<int> frame});

  Uint8List signChallenge({required List<int> challenge});

  Uint8List signWithTk({required String groupId, required List<int> nonce});

  (Uint8List, Uint8List, Uint8List, BigInt, Uint8List, bool) toParts();

  BGroupContext upgrade();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BSecretsFactory>>
abstract class BSecretsFactory implements RustOpaqueInterface {
  /// Applies cipher text and encryption key, return plain text
  Uint8List decrypt({required List<int> ciphertext, required List<int> okm});

  /// Returns cipher text and encryption key
  (Uint8List, Uint8List) encrypt({required List<int> plaintext});

  Uint8List generateSecret();

  (Uint8List, Uint8List) generateSecretWithPublicKey();

  factory BSecretsFactory({required U8Array32 seed}) =>
      RustLib.instance.api.crateApiGroupContextBSecretsFactoryNew(seed: seed);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BUser>>
abstract class BUser implements RustOpaqueInterface {
  String id();

  String name();

  factory BUser({required String name, required List<int> publicKey}) => RustLib
      .instance
      .api
      .crateApiGroupContextBUserNew(name: name, publicKey: publicKey);
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
