// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Uint8List publicKeyFromSecretKey({required List<int> secretKey}) => RustLib
    .instance
    .api
    .crateApiGroupContextPublicKeyFromSecretKey(secretKey: secretKey);

(BGroupContext, Uint8List, Map<Uint8List, Uint8List>, List<Uint8List>)
createGroup({
  required List<int> identitySecretKey,
  required BUser user,
  required BGroupInfo groupInfo,
  required List<(Uint8List, Uint8List?)> identifiedMembersKeys,
  required BigInt unidentifiedMembersCount,
  required List<Uint8List> payloads,
}) => RustLib.instance.api.crateApiGroupContextCreateGroup(
  identitySecretKey: identitySecretKey,
  user: user,
  groupInfo: groupInfo,
  identifiedMembersKeys: identifiedMembersKeys,
  unidentifiedMembersCount: unidentifiedMembersCount,
  payloads: payloads,
);

(BGroupContext, Uint8List) createGroupFromIdentifiedInvite({
  required List<int> identitySecretKey,
  required List<int> spkSecretKey,
  required List<int> art,
  required List<int> invite,
  required BUser user,
}) => RustLib.instance.api.crateApiGroupContextCreateGroupFromIdentifiedInvite(
  identitySecretKey: identitySecretKey,
  spkSecretKey: spkSecretKey,
  art: art,
  invite: invite,
  user: user,
);

(BGroupContext, Uint8List) createGroupFromUnidentifiedInvite({
  required List<int> identitySecretKey,
  required List<int> art,
  required List<int> invite,
  required BUser user,
}) =>
    RustLib.instance.api.crateApiGroupContextCreateGroupFromUnidentifiedInvite(
      identitySecretKey: identitySecretKey,
      art: art,
      invite: invite,
      user: user,
    );

(Uint8List, Uint8List, BigInt, Uint8List) destructIdentifiedInvite({
  required List<int> invite,
  required List<int> identitySecretKey,
  required List<int> spkSecretKey,
}) => RustLib.instance.api.crateApiGroupContextDestructIdentifiedInvite(
  invite: invite,
  identitySecretKey: identitySecretKey,
  spkSecretKey: spkSecretKey,
);

(Uint8List, Uint8List, BigInt, Uint8List) destructUnidentifiedInvite({
  required List<int> invite,
}) => RustLib.instance.api.crateApiGroupContextDestructUnidentifiedInvite(
  invite: invite,
);

Uint8List signChallenge({
  required List<int> leafSecret,
  required String chatId,
  required List<int> nonce,
  required List<int> challenge,
  required BigInt epoch,
}) => RustLib.instance.api.crateApiGroupContextSignChallenge(
  leafSecret: leafSecret,
  chatId: chatId,
  nonce: nonce,
  challenge: challenge,
  epoch: epoch,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BGroupContext>>
abstract class BGroupContext implements RustOpaqueInterface {
  (Uint8List, Uint8List) addIdentifiedMember({
    required List<int> identityPublicKey,
    Uint8List? spkPublicKey,
    required List<Uint8List> payloads,
  });

  Future<(Uint8List, Uint8List)> addUnidentifiedMember({
    required List<int> secretKey,
    required List<Uint8List> payloads,
  });

  Uint8List createFrame({required List<Uint8List> payloads});

  static BGroupContext fromParts({
    required List<int> identitySecretKey,
    required List<int> leafSecret,
    required List<int> art,
    required List<int> stk,
    required BigInt epoch,
    required List<int> groupInfo,
  }) => RustLib.instance.api.crateApiGroupContextBGroupContextFromParts(
    identitySecretKey: identitySecretKey,
    leafSecret: leafSecret,
    art: art,
    stk: stk,
    epoch: epoch,
    groupInfo: groupInfo,
  );

  BigInt getEpoch();

  (Uint8List, Uint8List, Uint8List, BigInt, Uint8List) intoParts();

  List<Uint8List> processFrame({required List<int> spFrame});

  Uint8List removeMember({
    required List<int> leafPublicKey,
    required List<int> payload,
  });

  Uint8List signWithTk({required String groupId, required List<int> nonce});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BGroupInfo>>
abstract class BGroupInfo implements RustOpaqueInterface {
  factory BGroupInfo({required String id, required String name}) => RustLib
      .instance
      .api
      .crateApiGroupContextBGroupInfoNew(id: id, name: name);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BSecretsFactory>>
abstract class BSecretsFactory implements RustOpaqueInterface {
  Uint8List generateSecret();

  (Uint8List, Uint8List) generateSecretWithPublicKey();

  factory BSecretsFactory({required U8Array32 seed}) =>
      RustLib.instance.api.crateApiGroupContextBSecretsFactoryNew(seed: seed);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BUser>>
abstract class BUser implements RustOpaqueInterface {
  factory BUser({required String id, required String name}) =>
      RustLib.instance.api.crateApiGroupContextBUserNew(id: id, name: name);
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
