// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_secret_with_public_key`, `generate_secret`, `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SecretsFactory>>
abstract class SecretsFactory implements RustOpaqueInterface {
  static Future<SecretsFactory> default_() =>
      RustLib.instance.api.crateApiSecretsFactorySecretsFactoryDefault();
}
