name: Build and Release

on:
  push:
    # tags:
    # - 'v?[0-9]+.[0-9]+.[0-9]+'
    # - 'v?[0-9]+.[0-9]+.[0-9]+-[0-9]+'
    branches:
      - "**"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }} # replace to github.ref_name
  CACHE_REPO: ghcr.io/${{ github.repository }}/cache

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get -y install buildah

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login ghcr.io -u ${{ github.repository_owner }} --password-stdin               

      - name: Build Image
        run: |
          buildah bud \
          --layers \
          --cache-from $CACHE_REPO \
          --cache-to $CACHE_REPO \
          -t $IMAGE_NAME .

      - name: Push Image (tag)
        run: |
          buildah push $IMAGE_NAME          

  release:
    runs-on: ubuntu-latest
    needs: build
    name: Create Release
    steps:
      - uses: shrink/actions-docker-extract@v3
        name: Extract package
        id: extract
        with:
          image: $IMAGE_NAME
          path: /dist/1.1.0/* # replace to github.ref_name
          destination: "/packages"
      - name: Show Extracted Files
        run: ls -R packages